### ISSUE TITLE
Connecting views together

### ISSUE THREAD

**Issue by Machinewarlock** [bridgeatwaterloo/david#10]
Connect these pages in order: 
- [x] Homepage and setting up:
  Main page -> Check in page -> Username page ->Decision- are you happy with your username(loop back to username if no) -> on boarding ... 
- [x] Start & Questions:
  Holding page -> David to life -> Holding page ->Decision-where-David should go -> Holding page -> Decision- are you happy ->Holding page -> Decision clothing ->Holding page -> Decision emotion ->Holding page -> Decision-want-more ->Holding page -> Decision-are-you-finished -> ...
- [x] Review page:
  How was David -> Would you see David again -> Thank you
- [x] dashboard app that has names of every view and user of dashboard app can choose the next view when it is time
- [x] Dashboard app updates firebase with chosen next view 

Refer to flow chart for full overview:
https://files.slack.com/files-pri/T1K57EFP0-F1UEKFH1S/david_flow-in-progress.png

**Comment by LeticiaBriscoe** [comment]
Resolved in #19
