### ISSUE TITLE
Create a view switcher

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#13]
Any time the user lands on the holding view, clicking the button should check the current view in firebase, and redirect them if it changes
####  Acceptance Criteria
- [x] App keeps track of current view
- [x] Button on holding page gets next view from firebase
- [x] If current view and next view are the same, user is told to look at the dance
- [x] If current view and next view are different, redirect user to the next view

**Comment by francissmedley** [comment]
DONE, THANKS ALL THAT HELPED
