### ISSUE TITLE
Result Text 

### ISSUE THREAD

**Issue by francissmedley** [bridgeatwaterloo/david#134]
the font size for the animated text that displays the results, although this is only a problem for the decision-where-david view where usernames are all shown, so maybe find a way to only reduce the font-size for this view,
- [x] "Where David text" is on two lines with username
- [ ] Live results are top-left and look really cool
- [x] Epoq logo indicator is top-left

**Comment by LeticiaBriscoe** [comment]
live results outstanding. Transferred to issue #145
