### ISSUE TITLE
Homepage needs content explaining David

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#2]
The main homepage of the app can serve as our marketing website that can be shared in the week leading up to the festival. It should be mobile-first and clean and simple. 
#### Acceptance Criteria
- [x] Homepage displays an explanation of what David is
- [x] It shows the dates and times of the performances
- [x] It contains a link to a Google map of the performance
- [x] It contains a link to the Geolocation checkin page for when the audience are at Strive
- [x] It contains Twitter and Facebook sharing buttons
- [x] It has a video embedded of the original performance

**Comment by LeticiaBriscoe** [comment]
#46
