### ISSUE TITLE
Reaction to Data and projections 

### ISSUE THREAD

**Issue by CalcuttP** [bridgeatwaterloo/david#20]
Projections on Left and Right Panel on the result for David. For David I have done:

Function showDavidWord(word){
    alert(word);
    $('.change').html(word);
}
showDavidWord("Shoes");

For audience: 

the same thing but on middle panel. 

TBC on details on the aesthetic.

**Comment by aliblackwell** [comment]
@CalcuttP could you please add a description for this issue?
