### ISSUE TITLE
decision where is david

### ISSUE THREAD

**Issue by CrisGavril** [bridgeatwaterloo/david#23]
- [x] Working on the page where the user chooses david's position. at the moment I will just try to make a drag and drop pin that the user can move. 
- [x] The second step would be to sent the data to the firebase, 
- [x] After that the position will be chosen based on the position one user selected, the user's decision will be randomly chosen.

Please feel free to help and give any ideas.

**Comment by aliblackwell** [comment]
@CrisGavril thinking about this, I think your idea of dividing it up into a grid of four is probably the best and easiest way of doing it. Then it's as simple as a tap on each area and sending the ID of that grid. It could be left, center, right, front, center, back leading to a grid of nine?
