### ISSUE TITLE
App View: david-to-life

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#4]
### Acceptance Criteria
- [x] There is a new view called david-to-life within /app
- [x] Taps are counted
- [x] When the user has tapped more than ten times, a function called saveUserFinishedTapping or similar is called that updates the database with the user's name

**Comment by kimberleynyam** [comment]
https://codepen.io/chrisgannon/pen/waaByJ - possible animation idea

**Comment by aliblackwell** [comment]
Hey @kimberleynyam, this one looks very similar but much simpler: http://codepen.io/nod2007/pen/JXzJvq.

**Comment by LeticiaBriscoe** [comment]
This is now completed in the davidToLife view

**Comment by LeticiaBriscoe** [comment]
Resolved in pull request #18
