### ISSUE TITLE
Projection View: david-to-life

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#5]
#### View
- [x] The projector displays a heartbeat
#### Logic
- [x] As more taps come into the database, the heartbeat increases
- [x] The projection view listens to the endpoint in Firebase where names are stored when they have tapped ten times. See #4 
- [ ] When a new username appears in the database, this is displayed on the screen

**Comment by kimberleynyam** [comment]
https://codepen.io/chrisgannon/pen/waaByJ - possible animation idea
