### ISSUE TITLE
Global stylesheet

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#6]
#### Acceptance Criteria
- [ ] Fonts chosen and implemented
- [ ] Color scheme chosen and implemented
- [ ] Global styles applied to all views

**Comment by Oye247** [comment]
Hi Ali, What are you looking to have done to these? Apologies, if they have already been resolved.

**Comment by aliblackwell** [comment]
Hey Oye, Kim picked this up, but is not here tomorrow so it's definitely
something you could look at!

**Comment by LeticiaBriscoe** [comment]
Done in #64
