### ISSUE TITLE
Enter Username - button or no button, that is the question (iPhone)

### ISSUE THREAD

**Issue by MrPyroMeiniac** [bridgeatwaterloo/david#70]
iPhone has to use enter button. This can either be modified or declared in on boarding.

**Comment by francissmedley** [comment]
shall we just add an extra button that also submits a form, so if they don't click enter they will see this button and just click it ?

**Comment by MrPyroMeiniac** [comment]
technically, if you were to add a button though, wouldn't that mean iPhone would then have two buttons?

**Comment by francissmedley** [comment]
yes, there would be two ways of entering the username, but one of them is the enter button on the iphone keyboard which i think quite a few people didn't think to press, so if we add another button that is on the main page, then they can click that if they don't click enter?

**Comment by Machinewarlock** [comment]
https://github.com/bridgeatwaterloo/david/pull/75 Done in this.
