### ISSUE TITLE
stage location directions from words to numbers

### ISSUE THREAD

**Issue by MrPyroMeiniac** [bridgeatwaterloo/david#74]
Turn directions into numbers  when sending position result to David

**Comment by francissmedley** [comment]
I think we decided not to show them in numbers to david, and to just show the directions that the audience have chosen because otherwise its a bit confusing for the audience to see numbers? anyway i have only just changed it back from numbers to directions

**Comment by MrPyroMeiniac** [comment]
fair enough, very much noted
