### ISSUE TITLE
Homepage marketing website 

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#77]
Homepage of the project is currently very simple and uninformative. It could do with some love.

**Comment by kimberleynyam** [comment]
Has this been done? and where can I see the current version of this?

**Comment by aliblackwell** [comment]
I think @Oye247 was working on it @kimberleynyam

**Comment by aliblackwell** [comment]
Perhaps in here: https://github.com/bridgeatwaterloo/david/tree/Oye247-patch-1
