### ISSUE TITLE
stage location: where's is David 

### ISSUE THREAD

**Issue by MrPyroMeiniac** [bridgeatwaterloo/david#90]
stage location results of each member to appear all over the screens of multiple users not just one by one on the one

change to 20secs on direction decision
tell the audience beforehand "that only the fastest
one will be chosen" (not necessarily true however)

**Comment by aliblackwell** [comment]
@CrisGavril were you going to look at this?!

**Comment by CrisGavril** [comment]
Not sure what the requirements mean. Could you please explain?

**Comment by mabatistussi** [comment]
I just fixed the issues from #92..
