### ISSUE TITLE
bug with are you happy

### ISSUE THREAD

**Issue by MrPyroMeiniac** [bridgeatwaterloo/david#93]
URL parameter isn't recognized as being different.
"are you happy" changed, looping back to 
"are you happy" isn't seen as a valid change

**Comment by aliblackwell** [comment]
At the moment, the projector router is looking to see if e.g. "/app/decision-are-you-happy/" equals "/app/decision-are-you-happy/" in the switch statement, so "/app/decision-are-you-happy/?iter=2" isn't working.

If we change this logic to see if the string contains the view name then we are good.

`"/app/decision-are-you-happy/?iter=2".indexOf("/app/decision-are-you-happy/")` will return 0, as it does contain it

if it doesn't contain it, it returns -1

So we would look for:

`(view).indexOf('/app/decision-are-you-happy') > -1` 

If this is true, we're on that view

@Machinewarlock does this make sense and are you happy to take on this issue?!
